<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Operator;

class OperatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $operators = [
            ['code' => 'B001', 'name' => 'TÜRK TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B002', 'name' => 'TURKCELL', 'status' => 'Kullanılıyor'],
            ['code' => 'B003', 'name' => 'VODAFONE', 'status' => 'Kullanılıyor'],
            ['code' => 'B004', 'name' => 'FENİX TELEKOM', 'status' => 'Korunuyor'],
            ['code' => 'B005', 'name' => 'FİXNET', 'status' => 'Kullanılıyor'],
            ['code' => 'B006', 'name' => 'UPTEL', 'status' => 'Korunuyor'],
            ['code' => 'B007', 'name' => 'BRİNGO TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B008', 'name' => 'TELCOCAT', 'status' => 'Korunuyor'],
            ['code' => 'B009', 'name' => 'BURSASPOR TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B011', 'name' => 'DEMİRÖREN TV', 'status' => 'Kullanılıyor'],
            ['code' => 'B012', 'name' => 'DORUK İLETİŞİM', 'status' => 'Kullanılıyor'],
            ['code' => 'B013', 'name' => 'SENA HABERLEŞME', 'status' => 'Kullanılıyor'],
            ['code' => 'B014', 'name' => 'TELUS', 'status' => 'Kullanılıyor'],
            ['code' => 'B015', 'name' => 'İŞ NET', 'status' => 'Kullanılıyor'],
            ['code' => 'B016', 'name' => 'VODAFONE NET', 'status' => 'Kullanılıyor'],
            ['code' => 'B017', 'name' => 'MİLLENİCOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B018', 'name' => 'SUPERONLİNE', 'status' => 'Kullanılıyor'],
            ['code' => 'B019', 'name' => 'TTNET', 'status' => 'Kullanılıyor'],
            ['code' => 'B020', 'name' => 'TURKNET', 'status' => 'Kullanılıyor'],
            ['code' => 'B021', 'name' => 'NETGSM', 'status' => 'Kullanılıyor'],
            ['code' => 'B022', 'name' => 'TTM TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B023', 'name' => 'CONNECTİST', 'status' => 'Kullanılıyor'],
            ['code' => 'B024', 'name' => 'ROİTEL', 'status' => 'Kullanılıyor'],
            ['code' => 'B025', 'name' => 'İKON TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B026', 'name' => '3C1B TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B028', 'name' => 'NAC TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B029', 'name' => 'DOĞUŞ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B030', 'name' => 'TÜRK TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B031', 'name' => 'SAHRA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B032', 'name' => 'IPC TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B033', 'name' => 'ELFE TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B035', 'name' => 'KOBİKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B036', 'name' => 'İSTELİA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B037', 'name' => 'FORTİS TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B038', 'name' => 'VERİMOR TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B040', 'name' => 'COMPATEL', 'status' => 'Kullanılıyor'],
            ['code' => 'B042', 'name' => 'VERİTA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B043', 'name' => 'POSTA GÜVERCİNİ', 'status' => 'Kullanılıyor'],
            ['code' => 'B044', 'name' => 'VERİSER', 'status' => 'Korunuyor'],
            ['code' => 'B045', 'name' => 'ÖZTEK HABERLEŞME', 'status' => 'Kullanılıyor'],
            ['code' => 'B046', 'name' => 'VATANNET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B047', 'name' => 'OMS BİLİŞİM', 'status' => 'Kullanılıyor'],
            ['code' => 'B050', 'name' => 'MOBİLİŞİM', 'status' => 'Kullanılıyor'],
            ['code' => 'B051', 'name' => 'HATNET', 'status' => 'Kullanılıyor'],
            ['code' => 'B052', 'name' => '1 NET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B056', 'name' => 'HAKAY TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B058', 'name' => 'NETGLOBAL', 'status' => 'Kullanılıyor'],
            ['code' => 'B064', 'name' => 'ÜNİVERSAL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B066', 'name' => 'DİGİCELL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B070', 'name' => 'GÜVEN TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B073', 'name' => 'GES MOBİL', 'status' => 'Kullanılıyor'],
            ['code' => 'B074', 'name' => 'VOİP TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B076', 'name' => 'OPLAVUS TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B078', 'name' => 'MAKSİ TEKNOLOJİ', 'status' => 'Kullanılıyor'],
            ['code' => 'B079', 'name' => 'NEHİRCELL', 'status' => 'Kullanılıyor'],
            ['code' => 'B080', 'name' => 'NETRA TELEKOM', 'status' => 'Korunuyor'],
            ['code' => 'B082', 'name' => 'AVRASYA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B085', 'name' => 'ÖDEMİŞ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B087', 'name' => 'MOBİLEKSEN', 'status' => 'Kullanılıyor'],
            ['code' => 'B092', 'name' => 'İLG TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B094', 'name' => 'YENİ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B095', 'name' => 'AVENCOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B098', 'name' => 'EBOS TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B101', 'name' => 'VİZYONNET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B103', 'name' => 'ELİTEL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B105', 'name' => 'CALLTÜRK TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B107', 'name' => 'AKONTEL', 'status' => 'Kullanılıyor'],
            ['code' => 'B108', 'name' => '3K TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B109', 'name' => 'ÇAĞRI SMS TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B112', 'name' => 'MEGA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B115', 'name' => 'TELSAM TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B117', 'name' => 'PRİVATE TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B120', 'name' => 'FİBER DSL', 'status' => 'Kullanılıyor'],
            ['code' => 'B121', 'name' => 'BUGİTEL', 'status' => 'Korunuyor'],
            ['code' => 'B125', 'name' => 'T SYSTEMS TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B127', 'name' => 'EFOR NET', 'status' => 'Kullanılıyor'],
            ['code' => 'B129', 'name' => 'BT BİLİŞİM', 'status' => 'Kullanılıyor'],
            ['code' => 'B131', 'name' => 'MİKROTEL', 'status' => 'Kullanılıyor'],
            ['code' => 'B135', 'name' => 'V.A.S. TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B136', 'name' => 'AKAR TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B137', 'name' => 'TELİNKA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B139', 'name' => 'SETAFON', 'status' => 'Kullanılıyor'],
            ['code' => 'B140', 'name' => 'ALFA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B141', 'name' => 'TESCOM TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B146', 'name' => 'AJANS TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B147', 'name' => 'GLOBALSTAR', 'status' => 'Kullanılıyor'],
            ['code' => 'B148', 'name' => 'ENTERA', 'status' => 'Kullanılıyor'],
            ['code' => 'B151', 'name' => 'BİLGE TELEKOM', 'status' => 'Korunuyor'],
            ['code' => 'B152', 'name' => 'RTEL GLOBAL', 'status' => 'Kullanılıyor'],
            ['code' => 'B153', 'name' => 'MUTLUCELL', 'status' => 'Kullanılıyor'],
            ['code' => 'B155', 'name' => 'GRİD TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B156', 'name' => 'MOVATEK', 'status' => 'Kullanılıyor'],
            ['code' => 'B158', 'name' => 'ZAGA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B161', 'name' => 'ÜNİVERSAL BİLİŞİM', 'status' => 'Kullanılıyor'],
            ['code' => 'B162', 'name' => 'VOİCE TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B164', 'name' => 'ONLİNE TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B165', 'name' => 'ORB TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B166', 'name' => 'CENGİZ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B169', 'name' => 'T FON TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B170', 'name' => 'VİP TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B173', 'name' => 'PLUŞ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B174', 'name' => 'ARTIADA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B175', 'name' => 'VERA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B176', 'name' => 'NETSA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B177', 'name' => 'AYYILDIZ GSM', 'status' => 'Kullanılıyor'],
            ['code' => 'B178', 'name' => 'ASİASEL', 'status' => 'Kullanılıyor'],
            ['code' => 'B182', 'name' => 'TTM İLETİŞİM', 'status' => 'Kullanılıyor'],
            ['code' => 'B183', 'name' => 'TB HABERLEŞME', 'status' => 'Kullanılıyor'],
            ['code' => 'B186', 'name' => 'EMARKA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B187', 'name' => 'SİNERJİ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B189', 'name' => 'DT TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B195', 'name' => 'AKDAĞ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B196', 'name' => 'MORNET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B197', 'name' => 'KOBİ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B200', 'name' => 'BİLİMCELL', 'status' => 'Kullanılıyor'],
            ['code' => 'B203', 'name' => 'EMN TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B204', 'name' => 'CLX TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B205', 'name' => 'MAYATEK TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B210', 'name' => 'DOĞA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B211', 'name' => 'AYYILDIZ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B219', 'name' => 'TÜRKHOST', 'status' => 'Kullanılıyor'],
            ['code' => 'B222', 'name' => 'BOSNET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B223', 'name' => 'ESER TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B224', 'name' => 'MOBİL SERVİSLER', 'status' => 'Kullanılıyor'],
            ['code' => 'B225', 'name' => 'ULAK TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B226', 'name' => 'FLYNET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B228', 'name' => 'E TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B229', 'name' => 'BULUTFON', 'status' => 'Kullanılıyor'],
            ['code' => 'B231', 'name' => 'PASİFİK TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B234', 'name' => 'İSOBİL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B236', 'name' => 'MODEXİ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B238', 'name' => 'İN-NO TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B241', 'name' => 'VOXBONE TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B243', 'name' => 'ORGANİK TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B244', 'name' => 'FONİVA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B245', 'name' => 'SESNET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B251', 'name' => 'ŞAHİN TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B254', 'name' => 'MESAJMERKEZİ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B255', 'name' => 'ZEOS TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B259', 'name' => 'KÜRESEL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B260', 'name' => 'SİGMA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B262', 'name' => 'RONİ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B270', 'name' => 'ASİSTAN TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B272', 'name' => 'CAN TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B273', 'name' => 'EVYAPAN TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B276', 'name' => 'MOBİCALL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B277', 'name' => 'SANAL SANTRAL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B279', 'name' => 'BEE TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B282', 'name' => 'TEKNOMOBİL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B287', 'name' => 'ALOCELL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B290', 'name' => 'COSMOSCELL', 'status' => 'Kullanılıyor'],
            ['code' => 'B293', 'name' => 'DİCLE TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B298', 'name' => 'TÜRKNET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B300', 'name' => 'TÜRKLAN TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B302', 'name' => 'EFECEL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B304', 'name' => 'MOBİLM TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B307', 'name' => 'KIRMIZI KARE TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B310', 'name' => 'TURKFON TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B311', 'name' => 'ZETA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B314', 'name' => 'ADNET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B315', 'name' => 'GOLD TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B317', 'name' => 'TELCOROUTE TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B323', 'name' => 'MOBİLGİL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B325', 'name' => 'ALC MOBİLE', 'status' => 'Kullanılıyor'],
            ['code' => 'B326', 'name' => 'E NET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B331', 'name' => 'CORVAŞ TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B337', 'name' => 'MOBİLKENT TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B340', 'name' => 'GLOBAL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B345', 'name' => 'TT INTERNATIONAL', 'status' => 'Kullanılıyor'],
            ['code' => 'B346', 'name' => 'TARGET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B348', 'name' => 'EXTRANET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B349', 'name' => 'TÜRKSAT', 'status' => 'Kullanılıyor'],
            ['code' => 'B350', 'name' => 'LABİRENT TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B351', 'name' => 'SONET TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B353', 'name' => 'DİNAMİK TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B354', 'name' => 'BİR TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B356', 'name' => 'USLUCAN TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B357', 'name' => '216 TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B360', 'name' => 'MEDİUM TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B361', 'name' => 'PELİCELL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B362', 'name' => 'DID TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B363', 'name' => 'BRİNGO TELEKOM', 'status' => 'Korunuyor'],
            ['code' => 'B364', 'name' => 'NİDA TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B365', 'name' => 'BAŞAKCELL TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B367', 'name' => 'İSTANBUL BT TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B370', 'name' => 'NUR KARMED TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B371', 'name' => 'TELEKOMAT', 'status' => 'Kullanılıyor'],
            ['code' => 'B372', 'name' => 'İNTERAKTİF TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B373', 'name' => 'SNC TELEKOM', 'status' => 'Kullanılıyor'],
            ['code' => 'B448', 'name' => 'TRABZONSPOR TELEKOM', 'status' => 'Kullanılıyor'],
        ];

        foreach ($operators as $operator) {
            Operator::create($operator);
        }
    }
}
